doctrine:
    orm:
        mappings:
            ApiEntity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Api/Module/Entity'
                prefix: 'App\Api\Module\Entity'
                alias: Entity
